# -*- coding: utf-8 -*-
"""
体彩中文队名 → 英文规范名映射表 (唯一权威源)

fetch_sporttery.py 与 result_fetcher.py 共用;
独立成模块避免导入脚本产生拉取副作用。
"""
from __future__ import annotations

CN_TO_EN_TEAM = {
    '巴黎圣日尔曼': 'Paris Saint-Germain',
    '阿斯顿维拉': 'Aston Villa',
    '普拉滕斯': 'Platense',
    '科金博联': 'Coquimbo Unido',
    '帕尔梅拉斯': 'Palmeiras',
    '波特诺山丘': 'Cerro Porteno',
    '皇家马德里': 'Real Madrid',
    '巴塞罗那': 'Barcelona',
    '拜仁慕尼黑': 'Bayern Munich',
    '曼城': 'Manchester City',
    '利物浦': 'Liverpool',
    '阿森纳': 'Arsenal',
    '切尔西': 'Chelsea',
    '多特蒙德': 'Borussia Dortmund',
    '国际米兰': 'Inter Milan',
    'AC米兰': 'AC Milan',
    '尤文图斯': 'Juventus',
    '马德里竞技': 'Atletico Madrid',
    '博卡青年': 'Boca Juniors',
    '河床': 'River Plate',
    '弗拉门戈': 'Flamengo',
    '圣保罗': 'Sao Paulo',
    '桑托斯': 'Santos',
    # 欧罗巴资格赛
    '克拉约瓦': 'Universitatea Craiova',
    '克拉约瓦大学': 'Universitatea Craiova',
    '库奥皮奥': 'KuPS',
    '帕福斯': 'Pafos',
    '萨尔茨堡': 'Salzburg',
    '雷克维京': 'Vikingur Reykjavik',
    '雷克雅未克维京人': 'Vikingur Reykjavik',
    '图恩': 'Thun',
    '流浪者': 'Rangers',
    '格拉斯哥流浪者': 'Rangers',
    '比亚韦': 'Jagiellonia',
    '比亚韦斯托克': 'Jagiellonia',
    '安德莱': 'Anderlecht',
    '安德莱赫特': 'Anderlecht',
    '塞萨洛': 'PAOK',
    '塞萨洛尼基': 'PAOK',
    '哈茨': 'Hearts',
    '本菲卡': 'Benfica',
    # 解放者杯
    '米拉索尔': 'Mirassol',
    '基多体大': 'LDU Quito',
    '基多体育大学': 'LDU Quito',
    '罗萨里奥': 'Rosario Central',
    '罗萨里奥中央': 'Rosario Central',
    '科林蒂安': 'Corinthians',
    # 沙特联
    '艾卜哈': 'Abha',
    '拉斯决心': 'Al Hazm',
    '利雅青年': 'Al Shabab',
    '利雅得青年': 'Al Shabab',
    '利雅得青年人': 'Al Shabab',
    '胡巴卡德': 'Al Qadsiah',
    '胡巴尔卡德西亚': 'Al Qadsiah',
    '新未来SC': 'Neom',
    '迈季迈阿宽广': 'Al Majmaah',
    '迈季宽广': 'Al Majmaah',
    '达曼协定': 'Al Ettifaq',
    '利雅得': 'Al Riyadh',
    '利雅得新月': 'Al Hilal',
    '哈马赫费萨利': 'Al Faisaly',
    # 日职/芬超/德乙/瑞超/挪超/荷甲荷乙/法乙/英冠/葡超 (8月14日)
    '东京绿茵': 'Tokyo Verdy',
    '柏太阳神': 'Kashiwa Reysol',
    '瓦萨': 'Vaasan PS',
    'TPS图尔库': 'TPS',
    'TPS图尔': 'TPS',
    '基尔': 'Holstein Kiel',
    '圣保利': 'St Pauli',
    '不伦瑞克': 'Braunschweig',
    '波鸿': 'Bochum',
    '埃尔夫斯堡': 'IF Elfsborg',
    '埃夫斯堡': 'IF Elfsborg',
    '韦斯特罗斯': 'Västerås SK',
    '韦斯特罗': 'Västerås SK',
    '罗森博格': 'Rosenborg',
    '维京': 'Viking FK',
    '特尔斯达': 'Telstar',
    '鹿特丹斯巴达': 'Sparta Rotterdam',
    '鹿斯巴达': 'Sparta Rotterdam',
    '瓦尔韦克': 'Waalwijk',
    '多德勒支': 'Dordrecht',
    '赫拉克勒斯': 'Heracles',
    '赫拉克勒': 'Heracles',
    '登博思': 'Den Bosch',
    '阿纳西': 'Annecy',
    '罗德兹': 'Rodez',
    '兰斯': 'Reims',
    '敦刻尔克': 'Dunkerque',
    '圣埃蒂安': 'St Etienne',
    '克莱蒙': 'Clermont',
    '伍尔弗汉普顿': 'Wolves',
    '伍尔弗': 'Wolves',
    '布莱克本': 'Blackburn',
    '里斯本竞技': 'Sp Lisbon',
    '里斯本': 'Sp Lisbon',
    '吉马良斯': 'Guimaraes',
    # 8月15日 16场补充 (英文名对齐 football-data.org / API-Football)
    '鹿岛鹿角': 'Kashima Antlers', '名古屋鲸八': 'Nagoya Grampus',
    '秋田蓝色闪电': 'Blaublitz Akita', '富山胜利': 'Kataller Toyama',
    '浦和红钻': 'Urawa Red Diamonds', '广岛三箭': 'Sanfrecce Hiroshima',
    '神户胜利船': 'Vissel Kobe', '东京FC': 'FC Tokyo',
    '首尔FC': 'FC Seoul', '大田市民': 'Daejeon Hana Citizen',
    '光州FC': 'Gwangju FC', '浦项制铁': 'Pohang Steelers',
    '柏林赫塔': 'Hertha BSC', '海登海姆': 'FC Heidenheim',
    '威廉二世': 'Willem II', '奈梅亨': 'NEC Nijmegen',
    '阿马多拉': 'Estrela da Amadora',
    '阿尔维卡': 'Alverca',
    '乌德勒支': 'FC Utrecht', '阿尔克马尔': 'AZ Alkmaar',
    '维塞乌': 'Academico Viseu', '圣克拉拉': 'Santa Clara',
    '阿拉维斯': 'Alaves', '赫塔费': 'Getafe',
    'SBV精英': 'Excelsior', 'PSV埃因霍温': 'PSV Eindhoven',
    '福图纳锡塔德': 'Fortuna Sittard', '坎布尔': 'Cambuur',
    '塞维利亚': 'Sevilla', '巴列卡诺': 'Rayo Vallecano',
    '里奥阿维': 'Rio Ave', '波尔图': 'Porto',
    # 8月16日 28场补充 (英文名对齐模型训练库)
    '德岛漩涡': 'Tokushima Vortis', '鸟栖沙岩': 'Sagan Tosu',
    '海牙': 'Den Haag', '格罗宁根': 'Groningen',
    '富川FC': 'Bucheon FC 1995', '全北现代': 'Jeonbuk Motors',
    '仁川联': 'Incheon United', '金泉尚武': 'Gimcheon Sangmu',
    '布鲁马波卡纳': 'IF Brommapojkarna', '厄尔格里特': 'Orgryte',
    '代格福什': 'Degerfors IF', 'IFK哥德堡': 'IFK Goteborg',
    '佐加顿斯': 'Djurgården', 'AIK索尔纳': 'AIK',
    '特温特': 'Twente', '兹沃勒': 'Zwolle',
    '费耶诺德': 'Feyenoord', '前进之鹰': 'Go Ahead Eagles',
    '奥勒松': 'Aalesund', '瓦勒伦加': 'Vålerenga IF',
    '曼彻斯特城': 'Man City',
    'AC奥卢': 'AC Oulu', '国际图尔库': 'Inter Turku',
    '葡萄牙国民': 'Nacional', '埃斯托里尔': 'Estoril',
    '卡尔马': 'Kalmar', '哈马比': 'Hammarby',
    '哥德堡盖斯': 'GAIS', '马尔默': 'Malmo FF',
    '阿贾克斯': 'Ajax', '海伦芬': 'Heerenveen',
    '伯恩利': 'Burnley', '西汉姆联': 'West Ham',
    '桑坦德竞技': 'Santander', '比利亚雷亚尔': 'Villarreal',
    '西班牙人': 'Espanol', '莱万特': 'Levante',
    '阿罗卡': 'Arouca', '摩雷伦斯': 'Moreirense',
    '腓特烈斯塔': 'Fredrikstad FK', '克里斯蒂安松': 'Kristiansund',
    '瓦斯科达伽马': 'Vasco da Gama', '法马利康': 'Famalicao',
    '马里迪莫': 'Maritimo', '布拉加': 'Sp Braga',
    '吉维森特': 'Gil Vicente', '纽约城': 'New York City',
    '费城联合': 'Philadelphia Union', '莫尔德': 'Molde',
    '特罗姆瑟': 'Tromso', '布兰': 'Brann',
    '汉坎': 'HamKam', '萨尔普斯堡': 'Sarpsborg 08',
    '桑纳菲尤尔': 'Sandefjord',
}
